CREATE DATABASE NaturalBF_BD;

USE NaturalBF_BD;

CREATE TABLE Usuario(
    ID_Usuario INT(11) NOT NULL AUTO_INCREMENT,
    Usuario VARCHAR(11) NOT NULL,
    Pass VARCHAR(11) NOT NULL,
    PRIMARY KEY (ID_Usuario)
);